title: Hyeonmin (Amber) Lee
logo: /assets/img/mylogo.png
description: >
  Post-master research assistant<br>
  Computational Clinical Science Laboratory<br>
  Seoul National University<br><br>
  <span class="sidebar-links">
    <a href="https://www.linkedin.com/in/hyeonmin-amber-lee" target="_blank" rel="noopener noreferrer">LinkedIn</a>
    <a href="https://x.com/hmamberlee" target="_blank" rel="noopener noreferrer">X</a>
    <a href="mailto:gusghk5050@snu.ac.kr">Email</a>
    <a href="/assets/pdf/CV_Hyeonmin.pdf">CV</a>
  </span>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
